"""
Static map definitions for all 28 Catan maps.

This is now a thin wrapper over `app.maps.rasterizer`, which generates maps
from polygon data in `backend/app/maps/data/polygons/<slug>.json`.

Historical note: the file used to contain hand-placed `_tile(q, r, ...)` lists
for every country. That approach didn't scale — see `logs/map_rasterizer_design.md`
for the pivot rationale.
"""

from typing import Callable, Dict

from app.game.models import MapData
from app.maps.rasterizer import build_map as _build_map


# Registry of all supported map slugs. Each entry lazily builds the map from
# its polygon file when called; cached on first build.
_MAP_CACHE: Dict[str, MapData] = {}


def _cached_builder(slug: str) -> Callable[[], MapData]:
    def build() -> MapData:
        if slug not in _MAP_CACHE:
            _MAP_CACHE[slug] = _build_map(slug)
        return _MAP_CACHE[slug]
    return build


# All 28 supported map slugs. Keep order stable for /maps API output.
_SLUGS = [
    # Standard maps (25)
    "china", "czech_republic", "japan", "usa", "europe", "uk",
    "australia", "brazil", "antarctica", "india", "canada",
    "russia", "egypt", "mexico", "korea", "indonesia",
    "new_zealand", "france", "germany", "argentina", "south_africa",
    "italy", "scandinavia", "spain", "turkey", "vietnam",
    # XL maps (3)
    "africa_xl", "eurasia_xl", "americas_xl",
]


MAP_REGISTRY: Dict[str, Callable[[], MapData]] = {
    slug: _cached_builder(slug) for slug in _SLUGS
}


def get_static_map(map_id: str) -> MapData:
    fn = MAP_REGISTRY.get(map_id)
    if fn is None:
        raise ValueError(f"Unknown map: {map_id}")
    return fn()


def africa_xl_map() -> MapData:
    tiles = [
        _tile(-3, 1, "hills", 5),
        _tile(-2, 1, "fields", 4),
        _tile(-2, 0, "forest", 5),
        _tile(-1, 1, "hills", 6),
        _tile(-1, 0, "mountains", 10),
        _tile(-1, -1, "fields", 8),
        _tile(-2, -1, "hills", 9),
        _tile(0, 0, "mountains", 3),
        _tile(0, -1, "pasture", 4),
        _tile(-1, -2, "pasture", 2),
        _tile(1, -2, "forest", 8),
        _tile(2, -2, "fields", 9),
        _tile(1, -1, "fields", 11),
        _tile(3, -2, "pasture", 6),
        _tile(3, -3, "pasture", 4),
        _tile(2, -1, "hills", 10),
        _tile(1, 1, "pasture", 10),
        _tile(2, 1, "forest", 11),
        _tile(2, 0, "forest", 3),
        _tile(-3, 2, "fields", 11),
        _tile(-2, 2, "mountains", 5),
        _tile(-3, 3, "fields", 6),
        _tile(0, 1, "forest", 3),
        _tile(-1, 2, "hills", 3),
        _tile(1, 0, "hills", 4),
        _tile(-5, 3, "fields", 8),
        _tile(-4, 3, "forest", 12),
        _tile(-4, 2, "forest", 9),
        _tile(-1, 3, "mountains", 6),
        _tile(0, 2, "forest", 10),
        _tile(-5, 2, "pasture", 9),
        _tile(-4, 1, "pasture", 3),
        _tile(-3, 0, "hills", 8),
        _tile(0, 3, "pasture", 11),
        _tile(1, 3, "desert"),
        _tile(1, 2, "fields", 6),
        _tile(-2, 3, "desert"),
        _tile(0, -2, "pasture", 5),
        _tile(2, -3, "mountains", 5),
        _tile(2, 2, "mountains", 9),
        _tile(3, -1, "mountains", 3),
        _tile(1, -3, "pasture", 4),
        _tile(3, 0, "forest", 8),
        _tile(0, -3, "forest", 11),
        _tile(3, 1, "fields", 10),
    ]
    ports = [
        _port(3, 0, ratio=3, side=1),
        _port(3, -3, ratio=3, side=0),
        _port(2, 2, ratio=3, side=5),
        _port(-1, 3, ratio=3, side=5),
        _port(3, 1, ratio=3, side=0),
        _port(-5, 2, ratio=3, side=4),
        _port(-4, 3, "wheat", ratio=2, side=4),
        _port(-5, 3, ratio=3, side=3),
        _port(1, 3, ratio=3, side=4),
        _port(0, -3, "brick", ratio=2, side=3),
        _port(1, -3, ratio=3, side=2),
        _port(3, -2, "sheep", ratio=2, side=1),
        _port(3, -1, "wood", ratio=2, side=0),
        _port(-3, 0, ratio=3, side=3),
        _port(-2, 3, "ore", ratio=2, side=4),
    ]
    return normalize_ports(MapData(map_id="africa_xl", tiles=tiles, ports=ports))


def americas_xl_map() -> MapData:
    tiles = [
        _tile(-4, 1, "pasture", 11),
        _tile(-3, 1, "hills", 3),
        _tile(-2, 1, "forest", 9),
        _tile(-2, 0, "pasture", 9),
        _tile(-3, 2, "pasture", 11),
        _tile(-1, 1, "pasture", 12),
        _tile(-1, 0, "mountains", 6),
        _tile(0, 0, "forest", 5),
        _tile(0, -1, "fields", 9),
        _tile(1, 0, "fields", 4),
        _tile(2, 0, "mountains", 4),
        _tile(3, -1, "forest", 5),
        _tile(4, -2, "mountains", 4),
        _tile(-2, 2, "hills", 6),
        _tile(-1, 2, "fields", 9),
        _tile(-2, 3, "desert"),
        _tile(0, 2, "forest", 5),
        _tile(0, 1, "fields", 3),
        _tile(1, 2, "pasture", 11),
        _tile(1, 1, "forest", 5),
        _tile(2, 1, "forest", 3),
        _tile(3, 0, "forest", 6),
        _tile(3, -2, "pasture", 8),
        _tile(2, -2, "fields", 3),
        _tile(3, -3, "forest", 10),
        _tile(-1, -1, "hills", 11),
        _tile(-2, -1, "forest", 8),
        _tile(1, -2, "fields", 10),
        _tile(1, -3, "desert"),
        _tile(0, -2, "pasture", 6),
        _tile(2, -1, "hills", 11),
        _tile(-4, 2, "fields", 9),
        _tile(-3, 0, "pasture", 3),
        _tile(-3, 3, "pasture", 2),
        _tile(-1, -2, "fields", 4),
        _tile(-1, 3, "fields", 10),
        _tile(1, -1, "hills", 6),
        _tile(2, -3, "mountains", 8),
        _tile(4, -3, "mountains", 5),
        _tile(4, -1, "hills", 10),
        _tile(-4, 3, "mountains", 4),
        _tile(0, -3, "mountains", 10),
        _tile(0, 3, "hills", 8),
    ]
    ports = [
        _port(1, 2, "wood", ratio=2, side=5),
        _port(3, 0, ratio=3, side=0),
        _port(4, -1, ratio=3, side=5),
        _port(4, -3, ratio=3, side=0),
        _port(0, -3, ratio=3, side=1),
        _port(3, -3, ratio=3, side=2),
        _port(-4, 2, ratio=3, side=3),
        _port(-2, 3, "brick", ratio=2, side=5),
        _port(-4, 3, "ore", ratio=2, side=5),
        _port(4, -2, "wheat", ratio=2, side=1),
        _port(0, 3, ratio=3, side=4),
        _port(-3, 0, "sheep", ratio=2, side=3),
        _port(-4, 1, ratio=3, side=4),
        _port(2, -3, ratio=3, side=1),
        _port(-1, -2, ratio=3, side=3),
    ]
    return normalize_ports(MapData(map_id="americas_xl", tiles=tiles, ports=ports))


def antarctica_map() -> MapData:
    tiles = [
        _tile(0, 0, "pasture", 6),
        _tile(0, 1, "pasture", 10),
        _tile(-1, 1, "forest", 3),
        _tile(-1, 0, "hills", 5),
        _tile(1, 0, "fields", 11),
        _tile(1, 1, "forest", 10),
        _tile(0, -1, "forest", 3),
        _tile(0, 2, "mountains", 2),
        _tile(1, -1, "fields", 9),
        _tile(-1, -1, "mountains", 8),
        _tile(-1, 2, "hills", 8),
        _tile(1, 2, "fields", 6),
        _tile(-2, 1, "mountains", 8),
        _tile(-2, 0, "fields", 9),
        _tile(2, 0, "pasture", 6),
        _tile(2, 1, "mountains", 12),
        _tile(2, -1, "forest", 9),
        _tile(-2, 2, "fields", 11),
        _tile(0, -2, "forest", 5),
        _tile(-2, -1, "hills", 4),
        _tile(0, 3, "fields", 5),
        _tile(2, 2, "pasture", 9),
        _tile(1, -2, "fields", 6),
        _tile(-1, -2, "mountains", 9),
        _tile(-1, 3, "pasture", 4),
        _tile(1, 3, "fields", 5),
        _tile(-3, 1, "desert"),
        _tile(-3, 0, "forest", 3),
        _tile(3, 0, "pasture", 10),
        _tile(3, 1, "forest", 6),
        _tile(2, -2, "hills", 5),
        _tile(-2, 3, "mountains", 4),
        _tile(-2, -2, "pasture", 8),
        _tile(2, 3, "fields", 10),
        _tile(-3, 2, "forest", 4),
        _tile(3, -1, "mountains", 3),
        _tile(-3, -1, "pasture", 11),
        _tile(3, 2, "hills", 4),
        _tile(0, -3, "forest", 10),
        _tile(0, 4, "hills", 3),
        _tile(1, -3, "hills", 11),
        _tile(-1, -3, "hills", 4),
        _tile(-1, 4, "forest", 11),
        _tile(1, 4, "forest", 10),
        _tile(3, -2, "pasture", 3),
        _tile(-3, 3, "mountains", 11),
        _tile(-2, 4, "desert"),
        _tile(2, -3, "pasture", 5),
        _tile(-3, 4, "fields", 8),
        _tile(3, -3, "pasture", 9),
    ]
    ports = [
        _port(3, 2, ratio=3, side=0),
        _port(2, -3, ratio=3, side=1),
        _port(-3, -1, ratio=3, side=2),
        _port(3, 0, "ore", ratio=2, side=1),
        _port(-1, 4, ratio=3, side=5),
        _port(-3, 2, ratio=3, side=4),
        _port(-3, 0, ratio=3, side=3),
        _port(-1, -3, ratio=3, side=2),
        _port(3, -1, "sheep", ratio=2, side=0),
        _port(1, 4, ratio=3, side=5),
        _port(-2, -2, ratio=3, side=3),
        _port(3, -2, "wheat", ratio=2, side=1),
        _port(-2, 4, "wood", ratio=2, side=4),
        _port(3, -3, ratio=3, side=2),
        _port(1, -3, "brick", ratio=2, side=2),
    ]
    return normalize_ports(MapData(map_id="antarctica", tiles=tiles, ports=ports))


def argentina_map() -> MapData:
    tiles = [
        _tile(0, 1, "fields", 9),
        _tile(0, 0, "mountains", 4),
        _tile(-1, 1, "forest", 3),
        _tile(1, 1, "desert"),
        _tile(-1, 0, "hills", 10),
        _tile(0, 2, "pasture", 11),
        _tile(1, 0, "forest", 8),
        _tile(-1, 2, "forest", 8),
        _tile(1, 2, "fields", 6),
        _tile(0, -1, "hills", 12),
        _tile(-2, 1, "mountains", 10),
        _tile(-1, -1, "pasture", 4),
        _tile(1, -1, "fields", 11),
        _tile(-2, 0, "pasture", 3),
        _tile(2, 1, "fields", 11),
        _tile(2, 0, "hills", 10),
        _tile(0, 3, "mountains", 5),
        _tile(-2, 2, "fields", 2),
        _tile(2, 2, "mountains", 4),
        _tile(-1, 3, "hills", 3),
        _tile(1, 3, "mountains", 5),
        _tile(-2, -1, "pasture", 6),
        _tile(2, -1, "forest", 5),
        _tile(0, -2, "pasture", 6),
        _tile(-2, 3, "forest", 3),
        _tile(-1, -2, "fields", 9),
        _tile(1, -2, "forest", 9),
        _tile(2, -2, "pasture", 8),
    ]
    ports = [
        _port(2, 1, ratio=3, side=1),
        _port(-1, 3, ratio=3, side=5),
        _port(-2, 0, "wood", ratio=2, side=4),
        _port(2, -2, ratio=3, side=1),
        _port(-2, 1, "wheat", ratio=2, side=3),
        _port(1, 3, ratio=3, side=0),
        _port(-2, -1, "ore", ratio=2, side=2),
        _port(-2, 2, "sheep", ratio=2, side=4),
        _port(2, 0, "brick", ratio=2, side=0),
        _port(0, -2, ratio=3, side=2),
    ]
    return normalize_ports(MapData(map_id="argentina", tiles=tiles, ports=ports))


def australia_map() -> MapData:
    tiles = [
        _tile(0, 0, "pasture", 5),
        _tile(-1, 0, "forest", 10),
        _tile(0, -1, "fields", 2),
        _tile(-1, -1, "fields", 3),
        _tile(0, 1, "hills", 9),
        _tile(1, 0, "mountains", 8),
        _tile(-1, 1, "desert"),
        _tile(1, -1, "forest", 3),
        _tile(1, 1, "hills", 4),
        _tile(-2, 0, "hills", 8),
        _tile(0, -2, "fields", 11),
        _tile(-2, -1, "mountains", 10),
        _tile(-1, -2, "mountains", 6),
        _tile(-2, 1, "fields", 5),
        _tile(1, -2, "pasture", 11),
        _tile(0, 2, "forest", 5),
        _tile(2, 0, "mountains", 10),
        _tile(-1, 2, "fields", 4),
        _tile(2, -1, "pasture", 4),
        _tile(1, 2, "fields", 11),
        _tile(2, 1, "forest", 3),
        _tile(-3, 0, "hills", 9),
        _tile(0, -3, "forest", 4),
        _tile(-2, 2, "pasture", 6),
        _tile(-3, 1, "mountains", 3),
        _tile(1, -3, "hills", 8),
        _tile(2, -2, "forest", 6),
        _tile(-3, 2, "pasture", 12),
        _tile(2, -3, "pasture", 9),
    ]
    ports = [
        _port(2, 0, ratio=3, side=1),
        _port(-2, -1, "ore", ratio=2, side=2),
        _port(2, -3, "brick", ratio=2, side=0),
        _port(2, -1, "wheat", ratio=2, side=0),
        _port(1, -3, "wood", ratio=2, side=1),
        _port(2, 1, ratio=3, side=0),
        _port(-3, 0, ratio=3, side=3),
        _port(-2, 2, ratio=3, side=4),
        _port(-3, 2, "sheep", ratio=2, side=5),
        _port(0, 2, ratio=3, side=4),
    ]
    return normalize_ports(MapData(map_id="australia", tiles=tiles, ports=ports))


def brazil_map() -> MapData:
    tiles = [
        _tile(0, 0, "mountains", 4),
        _tile(0, 1, "fields", 4),
        _tile(-1, 0, "pasture", 8),
        _tile(-1, 1, "pasture", 10),
        _tile(1, 0, "fields", 11),
        _tile(1, 1, "forest", 11),
        _tile(0, -1, "mountains", 5),
        _tile(0, 2, "hills", 8),
        _tile(-1, -1, "desert"),
        _tile(1, -1, "pasture", 5),
        _tile(-1, 2, "pasture", 11),
        _tile(1, 2, "hills", 12),
        _tile(-2, 0, "forest", 4),
        _tile(2, 0, "forest", 6),
        _tile(-2, 1, "pasture", 3),
        _tile(2, 1, "forest", 2),
        _tile(2, -1, "fields", 3),
        _tile(0, 3, "hills", 5),
        _tile(0, -2, "mountains", 9),
        _tile(-2, 2, "fields", 6),
        _tile(1, -2, "mountains", 4),
        _tile(-1, 3, "mountains", 10),
        _tile(-3, 1, "fields", 6),
        _tile(3, 0, "forest", 10),
        _tile(-3, 2, "pasture", 3),
        _tile(-2, 3, "hills", 3),
        _tile(2, -2, "hills", 8),
        _tile(3, -1, "forest", 9),
        _tile(-3, 3, "desert"),
        _tile(3, -2, "fields", 9),
    ]
    ports = [
        _port(-2, 3, "wheat", ratio=2, side=4),
        _port(3, -2, "brick", ratio=2, side=2),
        _port(2, 1, ratio=3, side=0),
        _port(-3, 1, "wood", ratio=2, side=2),
        _port(1, -2, ratio=3, side=1),
        _port(-3, 2, "ore", ratio=2, side=4),
        _port(3, 0, ratio=3, side=5),
        _port(-1, -1, ratio=3, side=2),
        _port(0, 3, ratio=3, side=0),
        _port(0, -2, "sheep", ratio=2, side=3),
    ]
    return normalize_ports(MapData(map_id="brazil", tiles=tiles, ports=ports))


def canada_map() -> MapData:
    tiles = [
        _tile(0, 0, "hills", 11),
        _tile(0, -1, "hills", 5),
        _tile(-1, 0, "desert"),
        _tile(1, 0, "mountains", 8),
        _tile(-1, -1, "fields", 3),
        _tile(1, -1, "pasture", 9),
        _tile(0, 1, "desert"),
        _tile(0, -2, "pasture", 8),
        _tile(-1, 1, "pasture", 5),
        _tile(1, -2, "fields", 5),
        _tile(1, 1, "mountains", 11),
        _tile(-1, -2, "forest", 12),
        _tile(-2, 0, "fields", 9),
        _tile(2, 0, "forest", 11),
        _tile(2, -1, "forest", 10),
        _tile(-2, -1, "forest", 3),
        _tile(-2, 1, "pasture", 4),
        _tile(2, -2, "forest", 4),
        _tile(0, 2, "fields", 2),
        _tile(0, -3, "mountains", 9),
        _tile(-1, 2, "mountains", 6),
        _tile(1, -3, "hills", 10),
        _tile(3, -1, "forest", 6),
        _tile(-3, 0, "pasture", 4),
        _tile(-3, 1, "fields", 6),
        _tile(-2, 2, "hills", 3),
        _tile(2, -3, "mountains", 3),
        _tile(3, -2, "pasture", 4),
        _tile(-3, 2, "hills", 10),
        _tile(3, -3, "fields", 8),
    ]
    ports = [
        _port(3, -2, ratio=3, side=1),
        _port(-3, 1, ratio=3, side=3),
        _port(-1, 2, "wood", ratio=2, side=4),
        _port(3, -1, "ore", ratio=2, side=5),
        _port(2, -3, ratio=3, side=2),
        _port(0, -3, "sheep", ratio=2, side=2),
        _port(2, 0, "wheat", ratio=2, side=0),
        _port(-3, 2, "brick", ratio=2, side=5),
        _port(-3, 0, ratio=3, side=4),
        _port(-1, -2, ratio=3, side=3),
    ]
    return normalize_ports(MapData(map_id="canada", tiles=tiles, ports=ports))


def china_map() -> MapData:
    tiles = [
        _tile(-4, 2, "forest", 12),
        _tile(-3, 2, "pasture", 5),
        _tile(-3, 1, "forest", 11),
        _tile(-2, 2, "mountains", 10),
        _tile(-2, 1, "mountains", 9),
        _tile(-1, 2, "pasture", 3),
        _tile(-1, 1, "forest", 3),
        _tile(-1, 0, "desert"),
        _tile(0, 1, "forest", 10),
        _tile(0, 0, "pasture", 10),
        _tile(1, 1, "fields", 3),
        _tile(1, 0, "fields", 5),
        _tile(1, -1, "fields", 9),
        _tile(2, -1, "hills", 11),
        _tile(2, -2, "pasture", 8),
        _tile(2, 1, "mountains", 5),
        _tile(2, 0, "fields", 4),
        _tile(0, 2, "hills", 4),
        _tile(1, 2, "hills", 6),
        _tile(-2, 0, "hills", 8),
        _tile(0, -1, "fields", 4),
        _tile(-1, -1, "forest", 2),
        _tile(1, -2, "pasture", 9),
        _tile(0, -2, "mountains", 6),
    ]
    ports = [
        _port(2, 0, "ore", ratio=2, side=1),
        _port(-4, 2, ratio=3, side=3),
        _port(0, -2, "wheat", ratio=2, side=2),
        _port(2, -2, ratio=3, side=1),
        _port(0, 2, "sheep", ratio=2, side=5),
        _port(-2, 2, ratio=3, side=5),
        _port(-1, 2, "wood", ratio=2, side=4),
        _port(1, 2, "brick", ratio=2, side=0),
    ]
    return normalize_ports(MapData(map_id="china", tiles=tiles, ports=ports))


def egypt_map() -> MapData:
    tiles = [
        _tile(-2, -1, "forest", 4),
        _tile(-1, -1, "hills", 3),
        _tile(-2, 0, "fields", 11),
        _tile(0, -1, "hills", 12),
        _tile(0, -2, "pasture", 10),
        _tile(-1, 0, "mountains", 3),
        _tile(-2, 1, "forest", 6),
        _tile(1, -1, "hills", 8),
        _tile(1, -2, "hills", 9),
        _tile(0, 0, "forest", 9),
        _tile(-1, 1, "pasture", 11),
        _tile(-2, 2, "fields", 3),
        _tile(2, -1, "pasture", 5),
        _tile(2, -2, "desert"),
        _tile(1, 0, "mountains", 5),
        _tile(2, -3, "pasture", 10),
        _tile(0, 1, "mountains", 10),
        _tile(-1, 2, "mountains", 9),
        _tile(2, 0, "fields", 2),
        _tile(1, 1, "forest", 4),
        _tile(-1, -2, "fields", 4),
        _tile(0, 2, "forest", 8),
        _tile(1, -3, "fields", 5),
        _tile(0, -3, "pasture", 6),
    ]
    ports = [
        _port(2, 0, ratio=3, side=0),
        _port(-2, 0, "wheat", ratio=2, side=4),
        _port(0, -3, "brick", ratio=2, side=1),
        _port(2, -1, ratio=3, side=1),
        _port(2, -3, "wood", ratio=2, side=0),
        _port(0, 2, "sheep", ratio=2, side=4),
        _port(-2, 2, "ore", ratio=2, side=5),
        _port(-2, -1, ratio=3, side=3),
    ]
    return normalize_ports(MapData(map_id="egypt", tiles=tiles, ports=ports))


def eurasia_xl_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 5),
        _tile(0, -1, "forest", 8),
        _tile(1, 0, "forest", 11),
        _tile(1, -1, "fields", 11),
        _tile(-1, 0, "forest", 4),
        _tile(-1, -1, "forest", 3),
        _tile(0, -2, "forest", 5),
        _tile(1, -2, "forest", 9),
        _tile(2, -1, "desert"),
        _tile(0, 1, "hills", 6),
        _tile(1, 1, "fields", 10),
        _tile(2, 0, "pasture", 4),
        _tile(-1, 1, "fields", 4),
        _tile(2, -2, "hills", 4),
        _tile(-1, -2, "pasture", 6),
        _tile(2, 1, "fields", 6),
        _tile(-2, 0, "forest", 6),
        _tile(-2, -1, "pasture", 9),
        _tile(3, -1, "fields", 8),
        _tile(1, -3, "mountains", 11),
        _tile(0, -3, "fields", 5),
        _tile(3, 0, "fields", 9),
        _tile(0, 2, "mountains", 9),
        _tile(1, 2, "hills", 5),
        _tile(-2, 1, "pasture", 12),
        _tile(3, -2, "mountains", 3),
        _tile(2, -3, "pasture", 8),
        _tile(-1, 2, "fields", 10),
        _tile(-2, -2, "forest", 10),
        _tile(-1, -3, "mountains", 4),
        _tile(3, 1, "hills", 11),
        _tile(2, 2, "hills", 10),
        _tile(-3, 0, "hills", 5),
        _tile(3, -3, "pasture", 9),
        _tile(-2, 2, "desert"),
        _tile(4, -1, "mountains", 10),
        _tile(-3, -1, "hills", 6),
        _tile(1, -4, "forest", 8),
        _tile(4, 0, "forest", 8),
        _tile(0, -4, "forest", 5),
        _tile(0, 3, "fields", 6),
        _tile(1, 3, "pasture", 11),
        _tile(-3, 1, "fields", 3),
        _tile(4, -2, "hills", 4),
        _tile(2, -4, "mountains", 2),
        _tile(-3, 2, "pasture", 10),
        _tile(-1, 3, "mountains", 3),
        _tile(3, -4, "pasture", 9),
        _tile(4, -3, "pasture", 8),
        _tile(-2, 3, "pasture", 11),
        _tile(4, -4, "mountains", 3),
        _tile(-3, 3, "mountains", 3),
    ]
    ports = [
        _port(-3, 1, "ore", ratio=2, side=3),
        _port(4, -2, ratio=3, side=0),
        _port(2, 2, "brick", ratio=2, side=5),
        _port(-3, -1, ratio=3, side=2),
        _port(3, 1, "sheep", ratio=2, side=0),
        _port(-3, 3, ratio=3, side=3),
        _port(0, -4, "wheat", ratio=2, side=2),
        _port(1, 3, "wood", ratio=2, side=0),
        _port(4, -4, ratio=3, side=1),
        _port(1, -4, ratio=3, side=1),
        _port(-3, 0, ratio=3, side=4),
        _port(-2, -2, ratio=3, side=3),
        _port(-1, 3, ratio=3, side=4),
        _port(2, -4, ratio=3, side=2),
        _port(-3, 2, ratio=3, side=4),
    ]
    return normalize_ports(MapData(map_id="eurasia_xl", tiles=tiles, ports=ports))


def europe_map() -> MapData:
    tiles = [
        _tile(-1, 0, "mountains", 4),
        _tile(0, 0, "fields", 10),
        _tile(-1, 1, "pasture", 4),
        _tile(0, 1, "fields", 8),
        _tile(-2, 0, "forest", 6),
        _tile(-1, -1, "pasture", 10),
        _tile(-2, 1, "fields", 11),
        _tile(0, -1, "hills", 5),
        _tile(-2, -1, "hills", 10),
        _tile(1, 0, "mountains", 9),
        _tile(-1, 2, "hills", 3),
        _tile(1, 1, "forest", 9),
        _tile(0, 2, "hills", 3),
        _tile(1, -1, "pasture", 9),
        _tile(-2, 2, "pasture", 8),
        _tile(-3, 0, "forest", 5),
        _tile(-1, -2, "forest", 6),
        _tile(-3, 1, "fields", 11),
        _tile(0, -2, "forest", 5),
        _tile(-2, -2, "pasture", 9),
        _tile(-3, -1, "forest", 6),
        _tile(1, 2, "fields", 5),
        _tile(2, 0, "mountains", 6),
        _tile(-1, 3, "forest", 6),
        _tile(-3, 2, "forest", 4),
        _tile(1, -2, "pasture", 4),
        _tile(2, 1, "pasture", 3),
        _tile(0, 3, "mountains", 4),
        _tile(2, -1, "fields", 9),
        _tile(-2, 3, "mountains", 5),
        _tile(-1, -3, "forest", 11),
        _tile(-4, 0, "forest", 10),
        _tile(0, -3, "pasture", 11),
        _tile(-4, 1, "fields", 8),
        _tile(-3, 3, "pasture", 12),
        _tile(2, -2, "desert"),
        _tile(1, -3, "hills", 9),
        _tile(-4, 2, "pasture", 2),
        _tile(3, 0, "pasture", 4),
        _tile(-1, 4, "hills", 5),
        _tile(3, -1, "mountains", 3),
        _tile(-2, 4, "fields", 11),
        _tile(-4, 3, "forest", 8),
        _tile(2, -3, "hills", 11),
        _tile(0, -4, "fields", 10),
        _tile(-3, 4, "mountains", 8),
        _tile(1, -4, "desert"),
        _tile(3, -2, "mountains", 8),
        _tile(-4, 4, "mountains", 3),
        _tile(2, -4, "fields", 10),
        _tile(3, -3, "hills", 3),
        _tile(3, -4, "fields", 6),
    ]
    ports = [
        _port(-3, -1, "wheat", ratio=2, side=2),
        _port(-3, 4, "sheep", ratio=2, side=5),
        _port(-4, 3, ratio=3, side=3),
        _port(-1, 4, ratio=3, side=4),
        _port(3, 0, "brick", ratio=2, side=1),
        _port(0, 3, "ore", ratio=2, side=5),
        _port(3, -4, ratio=3, side=2),
        _port(-4, 2, ratio=3, side=4),
        _port(2, -4, ratio=3, side=1),
        _port(-4, 1, ratio=3, side=3),
        _port(2, 1, "wood", ratio=2, side=0),
        _port(-4, 0, ratio=3, side=4),
        _port(1, -4, ratio=3, side=2),
        _port(3, -3, ratio=3, side=0),
        _port(3, -2, ratio=3, side=1),
    ]
    return normalize_ports(MapData(map_id="europe", tiles=tiles, ports=ports))


def france_map() -> MapData:
    tiles = [
        _tile(-1, 0, "pasture", 11),
        _tile(0, 0, "hills", 9),
        _tile(-1, 1, "forest", 12),
        _tile(0, 1, "forest", 5),
        _tile(-1, -1, "hills", 3),
        _tile(0, -1, "pasture", 2),
        _tile(-2, 0, "fields", 3),
        _tile(-2, 1, "hills", 6),
        _tile(1, 0, "pasture", 4),
        _tile(1, 1, "hills", 10),
        _tile(-1, 2, "pasture", 5),
        _tile(-2, -1, "desert"),
        _tile(0, 2, "pasture", 10),
        _tile(1, -1, "mountains", 11),
        _tile(-1, -2, "forest", 8),
        _tile(-2, 2, "forest", 10),
        _tile(0, -2, "pasture", 9),
        _tile(1, 2, "mountains", 6),
        _tile(-3, 0, "fields", 4),
        _tile(-3, 1, "mountains", 9),
        _tile(2, 0, "fields", 8),
        _tile(2, 1, "forest", 4),
        _tile(1, -2, "fields", 6),
        _tile(2, -1, "fields", 11),
        _tile(-3, 2, "forest", 3),
        _tile(2, -2, "mountains", 5),
    ]
    ports = [
        _port(2, 1, "brick", ratio=2, side=5),
        _port(2, -2, ratio=3, side=0),
        _port(-1, 2, ratio=3, side=5),
        _port(2, -1, "wood", ratio=2, side=1),
        _port(0, -2, "sheep", ratio=2, side=1),
        _port(-3, 2, ratio=3, side=5),
        _port(2, 0, "wheat", ratio=2, side=0),
        _port(-3, 0, ratio=3, side=3),
        _port(0, 2, "ore", ratio=2, side=4),
    ]
    return normalize_ports(MapData(map_id="france", tiles=tiles, ports=ports))


def germany_map() -> MapData:
    tiles = [
        _tile(-3, 0, "forest", 5),
        _tile(-2, 0, "forest", 8),
        _tile(-3, 1, "hills", 5),
        _tile(-1, 0, "mountains", 10),
        _tile(-1, -1, "pasture", 3),
        _tile(-2, 1, "pasture", 10),
        _tile(-3, 2, "fields", 6),
        _tile(0, 0, "mountains", 12),
        _tile(0, -1, "fields", 3),
        _tile(-1, 1, "hills", 8),
        _tile(0, -2, "hills", 6),
        _tile(-2, 2, "mountains", 4),
        _tile(1, -1, "desert"),
        _tile(0, 1, "forest", 9),
        _tile(1, -2, "forest", 11),
        _tile(-1, 2, "pasture", 3),
        _tile(1, -3, "fields", 9),
        _tile(2, -3, "mountains", 10),
        _tile(-2, -1, "fields", 4),
        _tile(1, 0, "forest", 2),
        _tile(2, -2, "fields", 5),
        _tile(-1, -2, "pasture", 4),
        _tile(2, -1, "pasture", 9),
        _tile(0, -3, "hills", 11),
    ]
    ports = [
        _port(-1, 2, ratio=3, side=0),
        _port(-3, 1, "brick", ratio=2, side=4),
        _port(2, -3, "wheat", ratio=2, side=2),
        _port(-3, 2, "wood", ratio=2, side=3),
        _port(-2, -1, ratio=3, side=3),
        _port(-1, -2, ratio=3, side=2),
        _port(1, 0, "sheep", ratio=2, side=0),
        _port(0, 1, "ore", ratio=2, side=5),
    ]
    return normalize_ports(MapData(map_id="germany", tiles=tiles, ports=ports))


def india_map() -> MapData:
    tiles = [
        _tile(0, 0, "pasture", 6),
        _tile(0, -1, "fields", 5),
        _tile(1, 0, "forest", 4),
        _tile(1, -1, "forest", 11),
        _tile(-1, 0, "hills", 11),
        _tile(-1, -1, "hills", 6),
        _tile(0, -2, "desert"),
        _tile(0, 1, "mountains", 5),
        _tile(1, -2, "fields", 8),
        _tile(2, -1, "fields", 8),
        _tile(1, 1, "fields", 12),
        _tile(2, 0, "fields", 3),
        _tile(2, -2, "hills", 10),
        _tile(-1, -2, "desert"),
        _tile(-1, 1, "mountains", 9),
        _tile(2, 1, "pasture", 6),
        _tile(-2, 0, "pasture", 3),
        _tile(1, -3, "hills", 9),
        _tile(0, -3, "mountains", 8),
        _tile(1, 2, "pasture", 5),
        _tile(0, 2, "pasture", 4),
        _tile(-2, -1, "mountains", 9),
        _tile(3, -1, "forest", 10),
        _tile(3, 0, "mountains", 4),
        _tile(-2, 1, "forest", 10),
        _tile(-1, 2, "forest", 3),
        _tile(2, -3, "hills", 4),
        _tile(3, -2, "forest", 2),
        _tile(-2, 2, "pasture", 11),
        _tile(3, -3, "fields", 3),
    ]
    ports = [
        _port(2, 1, ratio=3, side=5),
        _port(1, -3, "wood", ratio=2, side=2),
        _port(-1, -2, "wheat", ratio=2, side=2),
        _port(3, -3, "ore", ratio=2, side=2),
        _port(-2, -1, ratio=3, side=3),
        _port(3, -2, ratio=3, side=1),
        _port(-2, 2, "sheep", ratio=2, side=3),
        _port(1, 2, ratio=3, side=4),
        _port(0, -3, "brick", ratio=2, side=3),
        _port(3, 0, ratio=3, side=0),
    ]
    return normalize_ports(MapData(map_id="india", tiles=tiles, ports=ports))


def indonesia_map() -> MapData:
    tiles = [
        _tile(-1, 0, "hills", 3),
        _tile(0, 0, "pasture", 10),
        _tile(-1, -1, "forest", 8),
        _tile(-1, 1, "desert"),
        _tile(-2, 0, "pasture", 12),
        _tile(0, -1, "mountains", 3),
        _tile(0, 1, "forest", 9),
        _tile(-2, -1, "forest", 9),
        _tile(-2, 1, "hills", 6),
        _tile(1, 0, "fields", 6),
        _tile(-1, -2, "forest", 3),
        _tile(1, -1, "pasture", 5),
        _tile(0, -2, "pasture", 4),
        _tile(-1, 2, "pasture", 11),
        _tile(1, 1, "mountains", 11),
        _tile(-3, 0, "hills", 6),
        _tile(0, 2, "hills", 8),
        _tile(-2, -2, "fields", 8),
        _tile(-3, -1, "fields", 10),
        _tile(-2, 2, "mountains", 10),
        _tile(-3, 1, "mountains", 4),
        _tile(1, -2, "forest", 2),
        _tile(1, 2, "pasture", 3),
        _tile(2, 0, "fields", 4),
        _tile(-3, 2, "forest", 5),
        _tile(2, -1, "fields", 5),
        _tile(2, 1, "fields", 11),
        _tile(2, -2, "mountains", 9),
    ]
    ports = [
        _port(0, 2, ratio=3, side=5),
        _port(-1, 2, "brick", ratio=2, side=4),
        _port(-3, 0, "sheep", ratio=2, side=4),
        _port(0, -2, ratio=3, side=2),
        _port(-2, -2, ratio=3, side=1),
        _port(-3, 2, "ore", ratio=2, side=3),
        _port(2, -2, "wheat", ratio=2, side=1),
        _port(2, 0, ratio=3, side=1),
        _port(2, 1, "wood", ratio=2, side=5),
        _port(-3, -1, ratio=3, side=2),
    ]
    return normalize_ports(MapData(map_id="indonesia", tiles=tiles, ports=ports))


def italy_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 5),
        _tile(0, -1, "hills", 4),
        _tile(-1, 0, "pasture", 11),
        _tile(-1, -1, "mountains", 3),
        _tile(1, 0, "fields", 4),
        _tile(0, 1, "pasture", 10),
        _tile(1, -1, "pasture", 6),
        _tile(-1, 1, "fields", 3),
        _tile(0, -2, "mountains", 11),
        _tile(-2, 0, "mountains", 12),
        _tile(-1, -2, "forest", 6),
        _tile(-2, -1, "forest", 10),
        _tile(1, 1, "pasture", 8),
        _tile(1, -2, "fields", 9),
        _tile(-2, 1, "mountains", 8),
        _tile(-2, -2, "forest", 3),
        _tile(2, 0, "pasture", 4),
        _tile(2, -1, "fields", 9),
        _tile(0, 2, "forest", 5),
        _tile(-1, 2, "hills", 6),
        _tile(0, -3, "desert"),
        _tile(2, 1, "mountains", 11),
        _tile(-1, -3, "forest", 3),
        _tile(1, 2, "hills", 5),
        _tile(-2, 2, "forest", 10),
        _tile(1, -3, "hills", 8),
        _tile(2, -2, "pasture", 2),
        _tile(2, -3, "fields", 9),
    ]
    ports = [
        _port(2, 1, "wood", ratio=2, side=5),
        _port(0, 2, ratio=3, side=4),
        _port(-2, -1, "sheep", ratio=2, side=3),
        _port(2, 0, ratio=3, side=0),
        _port(-1, 2, "brick", ratio=2, side=5),
        _port(2, -3, "wheat", ratio=2, side=0),
        _port(2, -1, ratio=3, side=1),
        _port(-2, 1, ratio=3, side=3),
        _port(0, -3, "ore", ratio=2, side=1),
        _port(-1, -3, ratio=3, side=3),
    ]
    return normalize_ports(MapData(map_id="italy", tiles=tiles, ports=ports))


def japan_map() -> MapData:
    tiles = [
        _tile(0, 0, "pasture", 11),
        _tile(1, 0, "hills", 10),
        _tile(0, -1, "forest", 8),
        _tile(1, -1, "pasture", 4),
        _tile(0, 1, "mountains", 5),
        _tile(-1, 0, "mountains", 5),
        _tile(1, 1, "desert"),
        _tile(-1, -1, "fields", 10),
        _tile(2, 0, "hills", 2),
        _tile(0, -2, "pasture", 9),
        _tile(-1, 1, "forest", 8),
        _tile(2, -1, "forest", 6),
        _tile(1, -2, "fields", 9),
        _tile(0, 2, "pasture", 6),
        _tile(-2, 0, "fields", 10),
        _tile(2, -2, "pasture", 4),
        _tile(-1, 2, "mountains", 4),
        _tile(-2, 1, "forest", 3),
        _tile(3, -1, "hills", 9),
        _tile(1, -3, "forest", 11),
        _tile(3, -2, "fields", 5),
        _tile(2, -3, "pasture", 6),
        _tile(-2, 2, "forest", 3),
        _tile(-1, 3, "hills", 3),
        _tile(-2, 3, "mountains", 11),
        _tile(3, -3, "fields", 12),
    ]
    ports = [
        _port(3, -3, "sheep", ratio=2, side=1),
        _port(2, 0, "brick", ratio=2, side=0),
        _port(-2, 1, ratio=3, side=4),
        _port(-1, -1, ratio=3, side=2),
        _port(1, -3, ratio=3, side=3),
        _port(-1, 3, ratio=3, side=4),
        _port(-2, 3, "ore", ratio=2, side=5),
        _port(-2, 2, "wheat", ratio=2, side=3),
        _port(-2, 0, "wood", ratio=2, side=3),
    ]
    return normalize_ports(MapData(map_id="japan", tiles=tiles, ports=ports))


def korea_map() -> MapData:
    tiles = [
        _tile(0, 0, "forest", 4),
        _tile(1, 0, "forest", 9),
        _tile(0, 1, "hills", 2),
        _tile(0, -1, "forest", 11),
        _tile(-1, 0, "desert"),
        _tile(1, 1, "forest", 5),
        _tile(1, -1, "hills", 9),
        _tile(-1, 1, "mountains", 5),
        _tile(-1, -1, "fields", 6),
        _tile(2, 0, "hills", 9),
        _tile(0, 2, "fields", 11),
        _tile(2, 1, "mountains", 5),
        _tile(0, -2, "forest", 11),
        _tile(1, 2, "fields", 4),
        _tile(2, -1, "pasture", 10),
        _tile(-2, 0, "pasture", 3),
        _tile(1, -2, "mountains", 8),
        _tile(-1, 2, "hills", 8),
        _tile(-2, 1, "pasture", 6),
        _tile(2, -2, "pasture", 10),
        _tile(-2, 2, "fields", 3),
        _tile(0, 3, "mountains", 6),
        _tile(-1, 3, "fields", 12),
        _tile(1, -3, "pasture", 3),
        _tile(-2, 3, "forest", 4),
        _tile(2, -3, "pasture", 10),
    ]
    ports = [
        _port(-2, 1, ratio=3, side=3),
        _port(1, 2, "ore", ratio=2, side=0),
        _port(-2, 3, "sheep", ratio=2, side=4),
        _port(2, 1, ratio=3, side=1),
        _port(0, 3, "brick", ratio=2, side=5),
        _port(2, 0, "wheat", ratio=2, side=0),
        _port(2, -1, "wood", ratio=2, side=1),
        _port(0, -2, ratio=3, side=3),
        _port(1, -3, ratio=3, side=2),
    ]
    return normalize_ports(MapData(map_id="korea", tiles=tiles, ports=ports))


def mexico_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 4),
        _tile(0, -1, "fields", 3),
        _tile(1, 0, "mountains", 9),
        _tile(1, -1, "mountains", 8),
        _tile(-1, 0, "forest", 8),
        _tile(0, 1, "pasture", 6),
        _tile(-1, -1, "fields", 5),
        _tile(1, 1, "hills", 4),
        _tile(0, -2, "pasture", 3),
        _tile(2, 0, "fields", 3),
        _tile(1, -2, "forest", 11),
        _tile(2, -1, "pasture", 12),
        _tile(-1, 1, "hills", 2),
        _tile(-1, -2, "pasture", 10),
        _tile(2, 1, "fields", 6),
        _tile(2, -2, "hills", 11),
        _tile(-2, 0, "pasture", 9),
        _tile(-2, -1, "pasture", 5),
        _tile(-2, 1, "forest", 5),
        _tile(3, 0, "mountains", 9),
        _tile(3, -1, "forest", 10),
        _tile(3, 1, "hills", 10),
        _tile(3, -2, "mountains", 11),
        _tile(-3, 0, "forest", 4),
        _tile(-3, 1, "desert"),
    ]
    ports = [
        _port(-3, 1, ratio=3, side=5),
        _port(3, -2, ratio=3, side=0),
        _port(-3, 0, "ore", ratio=2, side=4),
        _port(1, 1, ratio=3, side=4),
        _port(-1, 1, ratio=3, side=4),
        _port(3, 0, "wheat", ratio=2, side=1),
        _port(-1, -2, "sheep", ratio=2, side=3),
        _port(3, 1, "brick", ratio=2, side=5),
        _port(1, -2, "wood", ratio=2, side=2),
    ]
    return normalize_ports(MapData(map_id="mexico", tiles=tiles, ports=ports))


def new_zealand_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 8),
        _tile(0, 1, "forest", 5),
        _tile(1, 0, "forest", 11),
        _tile(1, 1, "fields", 10),
        _tile(-1, 0, "pasture", 3),
        _tile(0, -1, "hills", 4),
        _tile(-1, 1, "fields", 4),
        _tile(1, -1, "pasture", 9),
        _tile(0, 2, "forest", 8),
        _tile(2, 0, "hills", 5),
        _tile(1, 2, "forest", 3),
        _tile(2, 1, "desert"),
        _tile(-1, -1, "fields", 6),
        _tile(-1, 2, "hills", 11),
        _tile(2, -1, "pasture", 8),
        _tile(-2, 0, "fields", 10),
        _tile(0, -2, "hills", 12),
        _tile(-2, 1, "fields", 6),
        _tile(1, -2, "forest", 10),
        _tile(0, 3, "pasture", 11),
        _tile(3, 0, "pasture", 9),
        _tile(-2, 2, "mountains", 3),
        _tile(2, -2, "mountains", 5),
        _tile(-1, 3, "mountains", 2),
        _tile(-2, 3, "pasture", 6),
        _tile(3, -1, "mountains", 4),
        _tile(3, -2, "forest", 9),
    ]
    ports = [
        _port(3, -2, ratio=3, side=1),
        _port(-1, -1, "ore", ratio=2, side=3),
        _port(3, 0, "wood", ratio=2, side=0),
        _port(-2, 2, ratio=3, side=3),
        _port(-2, 1, ratio=3, side=4),
        _port(-2, 3, "brick", ratio=2, side=4),
        _port(-1, 3, ratio=3, side=5),
        _port(0, -2, "wheat", ratio=2, side=1),
        _port(2, 1, "sheep", ratio=2, side=5),
    ]
    return normalize_ports(MapData(map_id="new_zealand", tiles=tiles, ports=ports))


def russia_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 8),
        _tile(0, 1, "fields", 9),
        _tile(1, 0, "forest", 3),
        _tile(1, 1, "fields", 5),
        _tile(-1, 0, "fields", 12),
        _tile(-1, 1, "forest", 4),
        _tile(0, -1, "fields", 11),
        _tile(0, 2, "pasture", 8),
        _tile(1, -1, "hills", 9),
        _tile(1, 2, "forest", 4),
        _tile(-1, -1, "forest", 10),
        _tile(-1, 2, "pasture", 3),
        _tile(2, 0, "desert"),
        _tile(2, 1, "pasture", 8),
        _tile(-2, 0, "fields", 8),
        _tile(-2, 1, "pasture", 9),
        _tile(2, -1, "desert"),
        _tile(0, -2, "pasture", 3),
        _tile(2, 2, "pasture", 5),
        _tile(-2, -1, "hills", 4),
        _tile(0, 3, "mountains", 9),
        _tile(1, -2, "fields", 2),
        _tile(-2, 2, "forest", 11),
        _tile(-1, -2, "mountains", 9),
        _tile(1, 3, "mountains", 3),
        _tile(-1, 3, "forest", 10),
        _tile(3, 0, "fields", 4),
        _tile(3, 1, "pasture", 5),
        _tile(2, -2, "pasture", 8),
        _tile(-3, 0, "mountains", 5),
        _tile(-3, 1, "forest", 11),
        _tile(3, -1, "hills", 10),
        _tile(-2, 3, "mountains", 6),
        _tile(0, -3, "forest", 6),
        _tile(-3, 2, "forest", 8),
        _tile(0, 4, "forest", 6),
        _tile(1, -3, "fields", 11),
        _tile(-1, 4, "hills", 10),
        _tile(3, -2, "mountains", 11),
        _tile(4, 0, "mountains", 3),
        _tile(2, -3, "fields", 4),
        _tile(-3, 3, "fields", 10),
        _tile(-2, 4, "mountains", 5),
        _tile(-4, 1, "pasture", 6),
        _tile(4, -1, "hills", 10),
        _tile(-4, 2, "forest", 3),
        _tile(-3, 4, "hills", 5),
        _tile(3, -3, "mountains", 11),
        _tile(4, -2, "hills", 6),
        _tile(-4, 3, "pasture", 9),
        _tile(4, -3, "pasture", 4),
        _tile(-4, 4, "hills", 6),
    ]
    ports = [
        _port(-3, 4, ratio=3, side=4),
        _port(2, -3, "wood", ratio=2, side=2),
        _port(3, 1, ratio=3, side=5),
        _port(2, 2, ratio=3, side=0),
        _port(-2, 4, ratio=3, side=5),
        _port(-3, 0, "wheat", ratio=2, side=2),
        _port(-4, 3, ratio=3, side=3),
        _port(-4, 2, "ore", ratio=2, side=4),
        _port(0, 4, ratio=3, side=5),
        _port(4, -2, ratio=3, side=0),
        _port(-1, -2, "sheep", ratio=2, side=2),
        _port(3, -3, ratio=3, side=1),
        _port(4, 0, "brick", ratio=2, side=1),
        _port(4, -3, ratio=3, side=2),
        _port(-1, 4, ratio=3, side=4),
    ]
    return normalize_ports(MapData(map_id="russia", tiles=tiles, ports=ports))


def scandinavia_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 11),
        _tile(-1, 0, "hills", 9),
        _tile(0, -1, "forest", 4),
        _tile(0, 1, "forest", 10),
        _tile(1, 0, "desert"),
        _tile(-1, -1, "forest", 11),
        _tile(1, -1, "mountains", 5),
        _tile(-1, 1, "fields", 3),
        _tile(1, 1, "forest", 8),
        _tile(0, 2, "pasture", 5),
        _tile(2, 0, "mountains", 9),
        _tile(-2, 0, "pasture", 10),
        _tile(0, -2, "mountains", 10),
        _tile(-2, 1, "forest", 10),
        _tile(-1, 2, "mountains", 9),
        _tile(-2, -1, "fields", 11),
        _tile(1, -2, "fields", 6),
        _tile(2, -1, "pasture", 6),
        _tile(-1, -2, "pasture", 8),
        _tile(1, 2, "mountains", 4),
        _tile(2, 1, "hills", 9),
        _tile(2, -2, "forest", 5),
        _tile(-2, 2, "forest", 5),
        _tile(0, 3, "pasture", 5),
        _tile(3, 0, "forest", 8),
        _tile(-3, 0, "hills", 4),
        _tile(0, -3, "pasture", 9),
        _tile(-1, 3, "hills", 8),
        _tile(3, -1, "hills", 3),
        _tile(1, -3, "pasture", 10),
        _tile(-3, 1, "fields", 6),
        _tile(-3, 2, "forest", 3),
        _tile(-2, 3, "mountains", 10),
        _tile(2, -3, "fields", 11),
        _tile(3, -2, "mountains", 3),
        _tile(4, -1, "pasture", 11),
        _tile(1, -4, "hills", 4),
        _tile(-1, 4, "pasture", 5),
        _tile(-4, 1, "hills", 9),
        _tile(-3, 3, "pasture", 12),
        _tile(3, -3, "fields", 8),
        _tile(2, -4, "hills", 6),
        _tile(-2, 4, "desert"),
        _tile(4, -2, "fields", 3),
        _tile(-4, 2, "fields", 11),
        _tile(-4, 3, "fields", 6),
        _tile(-3, 4, "forest", 6),
        _tile(3, -4, "fields", 2),
        _tile(4, -3, "pasture", 4),
        _tile(-4, 4, "mountains", 3),
        _tile(4, -4, "forest", 4),
    ]
    ports = [
        _port(-3, 4, ratio=3, side=4),
        _port(0, 3, "wheat", ratio=2, side=5),
        _port(2, 1, ratio=3, side=5),
        _port(4, -4, ratio=3, side=2),
        _port(4, -2, ratio=3, side=0),
        _port(-1, 4, ratio=3, side=0),
        _port(-4, 2, ratio=3, side=3),
        _port(4, -1, "wood", ratio=2, side=1),
        _port(1, 2, ratio=3, side=0),
        _port(1, -4, "brick", ratio=2, side=2),
        _port(-2, -1, "ore", ratio=2, side=3),
        _port(3, 0, ratio=3, side=0),
        _port(-1, -2, "sheep", ratio=2, side=2),
        _port(4, -3, ratio=3, side=1),
        _port(-4, 4, ratio=3, side=3),
    ]
    return normalize_ports(MapData(map_id="scandinavia", tiles=tiles, ports=ports))


def south_africa_map() -> MapData:
    tiles = [
        _tile(-3, 1, "forest", 9),
        _tile(-2, 1, "fields", 10),
        _tile(-2, 0, "forest", 6),
        _tile(-3, 2, "pasture", 4),
        _tile(-1, 1, "fields", 8),
        _tile(-1, 0, "forest", 4),
        _tile(-2, 2, "hills", 4),
        _tile(-1, -1, "desert"),
        _tile(0, 0, "mountains", 11),
        _tile(0, -1, "pasture", 8),
        _tile(0, -2, "pasture", 2),
        _tile(1, -1, "hills", 5),
        _tile(1, -2, "fields", 11),
        _tile(1, -3, "mountains", 5),
        _tile(2, -2, "pasture", 12),
        _tile(2, -3, "forest", 3),
        _tile(2, -4, "forest", 6),
        _tile(2, -1, "fields", 3),
        _tile(1, 0, "mountains", 9),
        _tile(0, 1, "hills", 3),
        _tile(-1, 2, "pasture", 10),
    ]
    ports = [
        _port(2, -4, ratio=3, side=1),
        _port(-2, 2, ratio=3, side=4),
        _port(2, -1, "ore", ratio=2, side=0),
        _port(-1, -1, "wood", ratio=2, side=2),
        _port(-3, 1, "brick", ratio=2, side=4),
        _port(-3, 2, "wheat", ratio=2, side=3),
        _port(0, 1, "sheep", ratio=2, side=0),
    ]
    return normalize_ports(MapData(map_id="south_africa", tiles=tiles, ports=ports))


def spain_map() -> MapData:
    tiles = [
        _tile(0, 1, "forest", 2),
        _tile(0, 0, "hills", 11),
        _tile(1, 1, "forest", 4),
        _tile(1, 0, "hills", 9),
        _tile(-1, 1, "fields", 6),
        _tile(-1, 0, "forest", 5),
        _tile(0, 2, "mountains", 3),
        _tile(1, 2, "mountains", 6),
        _tile(0, -1, "forest", 8),
        _tile(1, -1, "forest", 9),
        _tile(-1, 2, "fields", 10),
        _tile(2, 1, "fields", 3),
        _tile(2, 0, "forest", 8),
        _tile(-1, -1, "mountains", 4),
        _tile(-2, 1, "pasture", 10),
        _tile(-2, 0, "fields", 4),
        _tile(0, 3, "pasture", 11),
        _tile(2, -1, "hills", 5),
        _tile(-2, 2, "pasture", 9),
        _tile(0, -2, "fields", 12),
        _tile(-1, 3, "desert"),
        _tile(1, -2, "mountains", 11),
        _tile(3, 0, "fields", 3),
        _tile(2, -2, "pasture", 8),
        _tile(-2, 3, "pasture", 6),
        _tile(3, -1, "hills", 5),
        _tile(3, -2, "pasture", 10),
    ]
    ports = [
        _port(-2, 1, ratio=3, side=3),
        _port(-2, 0, "ore", ratio=2, side=2),
        _port(1, -2, "sheep", ratio=2, side=2),
        _port(3, 0, ratio=3, side=5),
        _port(0, 3, ratio=3, side=5),
        _port(-2, 3, "wood", ratio=2, side=3),
        _port(0, -2, "brick", ratio=2, side=1),
        _port(3, -2, "wheat", ratio=2, side=2),
        _port(-1, 3, ratio=3, side=4),
    ]
    return normalize_ports(MapData(map_id="spain", tiles=tiles, ports=ports))


def turkey_map() -> MapData:
    tiles = [
        _tile(0, 0, "mountains", 9),
        _tile(0, 1, "mountains", 3),
        _tile(1, 0, "forest", 11),
        _tile(1, 1, "fields", 6),
        _tile(-1, 0, "pasture", 8),
        _tile(-1, 1, "forest", 2),
        _tile(0, -1, "hills", 5),
        _tile(0, 2, "forest", 4),
        _tile(1, -1, "fields", 6),
        _tile(1, 2, "fields", 12),
        _tile(2, 0, "pasture", 3),
        _tile(2, 1, "mountains", 9),
        _tile(-1, -1, "mountains", 3),
        _tile(-1, 2, "mountains", 3),
        _tile(-2, 0, "forest", 10),
        _tile(2, -1, "pasture", 11),
        _tile(-2, 1, "fields", 4),
        _tile(2, 2, "forest", 8),
        _tile(0, -2, "pasture", 5),
        _tile(1, -2, "fields", 10),
        _tile(0, 3, "fields", 6),
        _tile(-2, -1, "hills", 11),
        _tile(1, 3, "pasture", 5),
        _tile(-1, -2, "desert"),
        _tile(-2, 2, "forest", 8),
        _tile(-1, 3, "hills", 4),
        _tile(2, -2, "pasture", 9),
        _tile(-2, 3, "hills", 10),
    ]
    ports = [
        _port(0, -2, ratio=3, side=2),
        _port(2, 2, ratio=3, side=1),
        _port(-1, 3, "ore", ratio=2, side=4),
        _port(2, -2, ratio=3, side=1),
        _port(1, 3, "wheat", ratio=2, side=4),
        _port(-2, 1, "wood", ratio=2, side=4),
        _port(-2, 3, "brick", ratio=2, side=5),
        _port(-2, 0, ratio=3, side=3),
        _port(-1, -2, ratio=3, side=1),
        _port(-2, 2, "sheep", ratio=2, side=3),
    ]
    return normalize_ports(MapData(map_id="turkey", tiles=tiles, ports=ports))


def uk_map() -> MapData:
    tiles = [
        _tile(0, 0, "hills", 5),
        _tile(0, -1, "mountains", 10),
        _tile(1, 0, "forest", 11),
        _tile(1, -1, "mountains", 4),
        _tile(-1, 0, "forest", 8),
        _tile(-1, -1, "mountains", 3),
        _tile(0, 1, "fields", 9),
        _tile(1, 1, "forest", 9),
        _tile(0, -2, "fields", 9),
        _tile(-1, 1, "fields", 10),
        _tile(1, -2, "pasture", 3),
        _tile(2, 0, "hills", 6),
        _tile(2, -1, "hills", 4),
        _tile(-1, -2, "mountains", 6),
        _tile(-2, 0, "fields", 11),
        _tile(-2, -1, "pasture", 12),
        _tile(2, 1, "hills", 4),
        _tile(0, 2, "fields", 10),
        _tile(2, -2, "forest", 8),
        _tile(1, 2, "pasture", 6),
        _tile(-2, 1, "desert"),
        _tile(0, -3, "pasture", 11),
        _tile(-1, 2, "pasture", 5),
        _tile(1, -3, "pasture", 3),
        _tile(-2, 2, "forest", 2),
        _tile(2, -3, "forest", 5),
    ]
    ports = [
        _port(2, -1, ratio=3, side=1),
        _port(-2, 2, ratio=3, side=3),
        _port(0, 2, "ore", ratio=2, side=5),
        _port(2, -3, "wheat", ratio=2, side=0),
        _port(-2, -1, "brick", ratio=2, side=4),
        _port(2, 1, "sheep", ratio=2, side=0),
        _port(-1, -2, "wood", ratio=2, side=2),
        _port(1, -3, ratio=3, side=2),
        _port(1, 2, ratio=3, side=4),
    ]
    return normalize_ports(MapData(map_id="uk", tiles=tiles, ports=ports))


def usa_map() -> MapData:
    tiles = [
        _tile(0, 0, "pasture", 10),
        _tile(1, 0, "pasture", 10),
        _tile(0, 1, "desert"),
        _tile(1, 1, "pasture", 8),
        _tile(1, -1, "forest", 11),
        _tile(0, -1, "hills", 12),
        _tile(-1, 0, "pasture", 4),
        _tile(2, 0, "mountains", 3),
        _tile(-1, 1, "fields", 6),
        _tile(2, -1, "fields", 4),
        _tile(2, 1, "hills", 3),
        _tile(-1, -1, "mountains", 11),
        _tile(0, 2, "forest", 5),
        _tile(1, 2, "forest", 5),
        _tile(1, -2, "hills", 9),
        _tile(0, -2, "forest", 8),
        _tile(-1, 2, "mountains", 10),
        _tile(3, 0, "fields", 6),
        _tile(-2, 0, "fields", 9),
        _tile(2, -2, "fields", 3),
        _tile(-2, 1, "hills", 4),
        _tile(3, -1, "pasture", 2),
        _tile(-2, 2, "forest", 9),
        _tile(3, -2, "mountains", 5),
    ]
    ports = [
        _port(-2, 0, "sheep", ratio=2, side=3),
        _port(0, -2, "ore", ratio=2, side=2),
        _port(3, -1, "wheat", ratio=2, side=1),
        _port(2, 1, "brick", ratio=2, side=0),
        _port(-2, 2, ratio=3, side=3),
        _port(3, -2, "wood", ratio=2, side=2),
        _port(0, 2, ratio=3, side=4),
        _port(3, 0, ratio=3, side=5),
    ]
    return normalize_ports(MapData(map_id="usa", tiles=tiles, ports=ports))


def vietnam_map() -> MapData:
    tiles = [
        _tile(0, 0, "fields", 4),
        _tile(-1, 0, "pasture", 10),
        _tile(0, 1, "mountains", 9),
        _tile(-1, 1, "desert"),
        _tile(0, -1, "forest", 11),
        _tile(-1, -1, "fields", 5),
        _tile(1, 0, "hills", 11),
        _tile(1, 1, "pasture", 4),
        _tile(-2, 0, "forest", 10),
        _tile(1, -1, "forest", 9),
        _tile(-2, 1, "pasture", 9),
        _tile(0, 2, "hills", 3),
        _tile(-2, -1, "pasture", 6),
        _tile(-1, 2, "hills", 3),
        _tile(0, -2, "mountains", 4),
        _tile(-1, -2, "hills", 11),
        _tile(1, 2, "pasture", 8),
        _tile(2, 0, "forest", 6),
        _tile(1, -2, "fields", 12),
        _tile(2, 1, "fields", 2),
        _tile(-2, 2, "mountains", 8),
        _tile(2, -1, "fields", 3),
        _tile(-3, 0, "forest", 5),
        _tile(-3, 1, "forest", 5),
        _tile(-3, 2, "mountains", 10),
        _tile(2, -2, "pasture", 6),
    ]
    ports = [
        _port(1, 2, ratio=3, side=4),
        _port(2, 1, ratio=3, side=5),
        _port(1, -2, ratio=3, side=1),
        _port(2, -1, "sheep", ratio=2, side=0),
        _port(-2, 2, ratio=3, side=5),
        _port(-2, -1, "wheat", ratio=2, side=3),
        _port(-3, 1, "brick", ratio=2, side=4),
        _port(0, 2, "ore", ratio=2, side=5),
        _port(-1, -2, "wood", ratio=2, side=2),
    ]
    return normalize_ports(MapData(map_id="vietnam", tiles=tiles, ports=ports))

