import type { MapConfig, TerrainType } from '../types'

// 5-row preview grids — each row is a list of TerrainType cells

const P = (rows: TerrainType[][]): TerrainType[][] => rows

export const MAP_CONFIGS: MapConfig[] = [
  {
    id: 'random',
    name: '🎲 Random',
    description: 'Fully randomised board — different every game.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'hills', 'ocean'],
      ['ocean', 'fields', 'pasture', 'mountains', 'ocean'],
      ['ocean', 'desert', 'fields', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'china',
    name: '🇨🇳 China',
    description: 'Ore-heavy mainland with vast mountains and sparse ports.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'mountains', 'mountains', 'ocean'],
      ['ocean', 'mountains', 'desert', 'fields', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'japan',
    name: '🇯🇵 Japan',
    description: 'Four islands rich in ports — maritime trade nation.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'ocean', 'mountains', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean', 'ocean'],
      ['ocean', 'ocean', 'pasture', 'ocean', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'usa',
    name: '🇺🇸 USA',
    description: 'Wheat-dominant plains stretching coast to coast.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'fields', 'ocean'],
      ['ocean', 'fields', 'desert', 'fields', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'europe',
    name: '🇪🇺 Europe',
    description: 'Fertile fields and pastoral lands with many ports.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'fields', 'pasture', 'ocean'],
      ['ocean', 'pasture', 'desert', 'mountains', 'ocean'],
      ['ocean', 'mountains', 'hills', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'uk',
    name: '🇬🇧 UK',
    description: 'Sheep-rich island chain with ore in the highlands.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'pasture', 'mountains', 'ocean'],
      ['ocean', 'pasture', 'desert', 'pasture', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'australia',
    name: '🇦🇺 Australia',
    description: 'Vast desert interior — ore and sheep on the coasts.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'desert', 'mountains', 'ocean'],
      ['ocean', 'desert', 'desert', 'pasture', 'ocean'],
      ['ocean', 'fields', 'hills', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'brazil',
    name: '🇧🇷 Brazil',
    description: 'Dense Amazon rainforest — wood floods the market.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'forest', 'ocean'],
      ['ocean', 'forest', 'desert', 'fields', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'india',
    name: '🇮🇳 India',
    description: 'Ganges plains brimming with wheat and spice trade ports.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'fields', 'pasture', 'ocean'],
      ['ocean', 'fields', 'desert', 'fields', 'ocean'],
      ['ocean', 'pasture', 'hills', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'canada',
    name: '🇨🇦 Canada',
    description: 'Boreal forest nation — wood-rich with fertile prairies.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'forest', 'ocean'],
      ['ocean', 'forest', 'desert', 'fields', 'ocean'],
      ['ocean', 'fields', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'russia',
    name: '🇷🇺 Russia',
    description: 'Taiga and Ural mountains — wood and ore dominate.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'mountains', 'ocean'],
      ['ocean', 'forest', 'desert', 'mountains', 'ocean'],
      ['ocean', 'hills', 'fields', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'egypt',
    name: '🇪🇬 Egypt',
    description: 'Nile Valley wheat and pyramid brick — few ports.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'fields', 'hills', 'ocean'],
      ['ocean', 'fields', 'desert', 'mountains', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'mexico',
    name: '🇲🇽 Mexico',
    description: 'Silver mines and ranches — brick and sheep abound.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'hills', 'pasture', 'ocean'],
      ['ocean', 'hills', 'desert', 'pasture', 'ocean'],
      ['ocean', 'fields', 'mountains', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'korea',
    name: '🇰🇷 Korea',
    description: 'Mountainous peninsula — ore-heavy with few flat lands.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'mountains', 'mountains', 'ocean'],
      ['ocean', 'mountains', 'desert', 'hills', 'ocean'],
      ['ocean', 'hills', 'forest', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'indonesia',
    name: '🇮🇩 Indonesia',
    description: 'Tropical archipelago — endless wood and brick.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'ocean', 'hills', 'ocean'],
      ['ocean', 'forest', 'desert', 'forest', 'ocean'],
      ['ocean', 'ocean', 'pasture', 'ocean', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'new_zealand',
    name: '🇳🇿 New Zealand',
    description: 'Sheep paradise with dramatic alpine peaks.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'pasture', 'mountains', 'ocean'],
      ['ocean', 'pasture', 'desert', 'pasture', 'ocean'],
      ['ocean', 'mountains', 'forest', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'france',
    name: '🇫🇷 France',
    description: 'Balanced agricultural empire — wine, wheat and wood.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'fields', 'pasture', 'ocean'],
      ['ocean', 'forest', 'desert', 'fields', 'ocean'],
      ['ocean', 'pasture', 'mountains', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'germany',
    name: '🇩🇪 Germany',
    description: 'Black Forest timber meets Ruhr industrial ore.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'forest', 'mountains', 'ocean'],
      ['ocean', 'forest', 'desert', 'mountains', 'ocean'],
      ['ocean', 'fields', 'hills', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
  {
    id: 'antarctica',
    name: '🧊 Antarctica',
    description: 'Hardcore mode — nearly all desert, almost no resources.',
    preview: P([
      ['ocean', 'ocean', 'ocean', 'ocean'],
      ['ocean', 'desert', 'desert', 'ocean'],
      ['ocean', 'desert', 'mountains', 'desert', 'ocean'],
      ['ocean', 'desert', 'fields', 'ocean'],
      ['ocean', 'ocean', 'ocean', 'ocean'],
    ]),
  },
]
